[build]
  base = "frontend/"
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_BACKEND_URL = "https://mini-crm-backend-r2uj.onrender.com"

[[redirects]]
  from = "/api/*"
  to = "https://mini-crm-backend-r2uj.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
